UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=1;
UPDATE pkm SET evolution_code=1,evolution_condition='Level 16' WHERE pkm.pkm_code=2;
UPDATE pkm SET evolution_code=2,evolution_condition='Level 32' WHERE pkm.pkm_code=3;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=4;
UPDATE pkm SET evolution_code=4,evolution_condition='Level 16' WHERE pkm.pkm_code=5;
UPDATE pkm SET evolution_code=5,evolution_condition='Level 36' WHERE pkm.pkm_code=6;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=7;
UPDATE pkm SET evolution_code=7,evolution_condition='Level 16' WHERE pkm.pkm_code=8;
UPDATE pkm SET evolution_code=8,evolution_condition='Level 36' WHERE pkm.pkm_code=9;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=10;
UPDATE pkm SET evolution_code=10,evolution_condition='Level 7' WHERE pkm.pkm_code=11;
UPDATE pkm SET evolution_code=11,evolution_condition='Level 10' WHERE pkm.pkm_code=12;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=13;
UPDATE pkm SET evolution_code=13,evolution_condition='Level 7' WHERE pkm.pkm_code=14;
UPDATE pkm SET evolution_code=14,evolution_condition='Level 10' WHERE pkm.pkm_code=15;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=16;
UPDATE pkm SET evolution_code=16,evolution_condition='Level 18' WHERE pkm.pkm_code=17;
UPDATE pkm SET evolution_code=17,evolution_condition='Level 36' WHERE pkm.pkm_code=18;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=19;
UPDATE pkm SET evolution_code=19,evolution_condition='Level 20' WHERE pkm.pkm_code=20;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=21;
UPDATE pkm SET evolution_code=21,evolution_condition='Level 20' WHERE pkm.pkm_code=22;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=23;
UPDATE pkm SET evolution_code=23,evolution_condition='Level 22' WHERE pkm.pkm_code=24;
UPDATE pkm SET evolution_code=172,evolution_condition='Happiness' WHERE pkm.pkm_code=25;
UPDATE pkm SET evolution_code=25,evolution_condition='use Thunder Stone' WHERE pkm.pkm_code=26;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=27;
UPDATE pkm SET evolution_code=27,evolution_condition='Level 22' WHERE pkm.pkm_code=28;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=29;
UPDATE pkm SET evolution_code=29,evolution_condition='Level 16' WHERE pkm.pkm_code=30;
UPDATE pkm SET evolution_code=30,evolution_condition='use Moon Stone' WHERE pkm.pkm_code=31;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=32;
UPDATE pkm SET evolution_code=32,evolution_condition='Level 16' WHERE pkm.pkm_code=33;
UPDATE pkm SET evolution_code=33,evolution_condition='use Moon Stone' WHERE pkm.pkm_code=34;
UPDATE pkm SET evolution_code=173,evolution_condition='Happiness' WHERE pkm.pkm_code=35;
UPDATE pkm SET evolution_code=35,evolution_condition='use Moon Stone' WHERE pkm.pkm_code=36;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=37;
UPDATE pkm SET evolution_code=37,evolution_condition='use Fire Stone' WHERE pkm.pkm_code=38;
UPDATE pkm SET evolution_code=174,evolution_condition='Happiness' WHERE pkm.pkm_code=39;
UPDATE pkm SET evolution_code=39,evolution_condition='use Moon Stone' WHERE pkm.pkm_code=40;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=41;
UPDATE pkm SET evolution_code=41,evolution_condition='Level 22' WHERE pkm.pkm_code=42;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=43;
UPDATE pkm SET evolution_code=43,evolution_condition='Level 21' WHERE pkm.pkm_code=44;
UPDATE pkm SET evolution_code=44,evolution_condition='use Leaf Stone' WHERE pkm.pkm_code=45;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=46;
UPDATE pkm SET evolution_code=46,evolution_condition='Level 24' WHERE pkm.pkm_code=47;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=48;
UPDATE pkm SET evolution_code=48,evolution_condition='Level 31' WHERE pkm.pkm_code=49;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=50;
UPDATE pkm SET evolution_code=50,evolution_condition='Level 26' WHERE pkm.pkm_code=51;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=52;
UPDATE pkm SET evolution_code=52,evolution_condition='Level 28' WHERE pkm.pkm_code=53;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=54;
UPDATE pkm SET evolution_code=54,evolution_condition='Level 33' WHERE pkm.pkm_code=55;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=56;
UPDATE pkm SET evolution_code=56,evolution_condition='Level 28' WHERE pkm.pkm_code=57;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=58;
UPDATE pkm SET evolution_code=58,evolution_condition='use Fire Stone' WHERE pkm.pkm_code=59;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=60;
UPDATE pkm SET evolution_code=60,evolution_condition='Level 25' WHERE pkm.pkm_code=61;
UPDATE pkm SET evolution_code=61,evolution_condition='use Water Stone' WHERE pkm.pkm_code=62;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=63;
UPDATE pkm SET evolution_code=63,evolution_condition='Level 16' WHERE pkm.pkm_code=64;
UPDATE pkm SET evolution_code=64,evolution_condition='Trade' WHERE pkm.pkm_code=65;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=66;
UPDATE pkm SET evolution_code=66,evolution_condition='Level 28' WHERE pkm.pkm_code=67;
UPDATE pkm SET evolution_code=67,evolution_condition='Trade' WHERE pkm.pkm_code=68;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=69;
UPDATE pkm SET evolution_code=69,evolution_condition='Level 21' WHERE pkm.pkm_code=70;
UPDATE pkm SET evolution_code=70,evolution_condition='use Leaf Stone' WHERE pkm.pkm_code=71;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=72;
UPDATE pkm SET evolution_code=72,evolution_condition='Level 30' WHERE pkm.pkm_code=73;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=74;
UPDATE pkm SET evolution_code=74,evolution_condition='Level 25' WHERE pkm.pkm_code=75;
UPDATE pkm SET evolution_code=75,evolution_condition='Trade' WHERE pkm.pkm_code=76;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=77;
UPDATE pkm SET evolution_code=77,evolution_condition='Level 40' WHERE pkm.pkm_code=78;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=79;
UPDATE pkm SET evolution_code=79,evolution_condition='Level 37' WHERE pkm.pkm_code=80;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=81;
UPDATE pkm SET evolution_code=81,evolution_condition='Level 30' WHERE pkm.pkm_code=82;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=83;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=84;
UPDATE pkm SET evolution_code=84,evolution_condition='Level 31' WHERE pkm.pkm_code=85;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=86;
UPDATE pkm SET evolution_code=86,evolution_condition='Level 34' WHERE pkm.pkm_code=87;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=88;
UPDATE pkm SET evolution_code=88,evolution_condition='Level 38' WHERE pkm.pkm_code=89;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=90;
UPDATE pkm SET evolution_code=90,evolution_condition='use Water Stone' WHERE pkm.pkm_code=91;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=92;
UPDATE pkm SET evolution_code=92,evolution_condition='Level 25' WHERE pkm.pkm_code=93;
UPDATE pkm SET evolution_code=93,evolution_condition='Trade' WHERE pkm.pkm_code=94;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=95;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=96;
UPDATE pkm SET evolution_code=96,evolution_condition='Level 26' WHERE pkm.pkm_code=97;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=98;
UPDATE pkm SET evolution_code=98,evolution_condition='Level 28' WHERE pkm.pkm_code=99;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=100;
UPDATE pkm SET evolution_code=100,evolution_condition='Level 30' WHERE pkm.pkm_code=101;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=102;
UPDATE pkm SET evolution_code=102,evolution_condition='use Leaf Stone' WHERE pkm.pkm_code=103;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=104;
UPDATE pkm SET evolution_code=104,evolution_condition='Level 28' WHERE pkm.pkm_code=105;
UPDATE pkm SET evolution_code=236,evolution_condition='Level 20 with Attack greater than Defense' WHERE pkm.pkm_code=106;
UPDATE pkm SET evolution_code=236,evolution_condition='Level 20 with Attack less than Defense' WHERE pkm.pkm_code=107;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=108;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=109;
UPDATE pkm SET evolution_code=109,evolution_condition='Level 35' WHERE pkm.pkm_code=110;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=111;
UPDATE pkm SET evolution_code=111,evolution_condition='Level 42' WHERE pkm.pkm_code=112;
UPDATE pkm SET evolution_code=440,evolution_condition='Level up holding Oval Stone during day' WHERE pkm.pkm_code=113;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=114;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=115;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=116;
UPDATE pkm SET evolution_code=116,evolution_condition='Level 32' WHERE pkm.pkm_code=117;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=118;
UPDATE pkm SET evolution_code=118,evolution_condition='Level 33' WHERE pkm.pkm_code=119;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=120;
UPDATE pkm SET evolution_code=120,evolution_condition='use Water Stone' WHERE pkm.pkm_code=121;
UPDATE pkm SET evolution_code=439,evolution_condition='Level up with Mimic learned' WHERE pkm.pkm_code=122;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=123;
UPDATE pkm SET evolution_code=238,evolution_condition='Level 30' WHERE pkm.pkm_code=124;
UPDATE pkm SET evolution_code=239,evolution_condition='Level 30' WHERE pkm.pkm_code=125;
UPDATE pkm SET evolution_code=240,evolution_condition='Level 30' WHERE pkm.pkm_code=126;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=127;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=128;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=129;
UPDATE pkm SET evolution_code=129,evolution_condition='Level 20' WHERE pkm.pkm_code=130;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=131;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=132;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=133;
UPDATE pkm SET evolution_code=133,evolution_condition='use Water Stone' WHERE pkm.pkm_code=134;
UPDATE pkm SET evolution_code=133,evolution_condition='use Thunder Stone' WHERE pkm.pkm_code=135;
UPDATE pkm SET evolution_code=133,evolution_condition='use Fire Stone' WHERE pkm.pkm_code=136;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=137;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=138;
UPDATE pkm SET evolution_code=138,evolution_condition='Level 40' WHERE pkm.pkm_code=139;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=140;
UPDATE pkm SET evolution_code=140,evolution_condition='Level 40' WHERE pkm.pkm_code=141;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=142;
UPDATE pkm SET evolution_code=446,evolution_condition='Happiness' WHERE pkm.pkm_code=143;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=144;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=145;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=146;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=147;
UPDATE pkm SET evolution_code=147,evolution_condition='Level 30' WHERE pkm.pkm_code=148;
UPDATE pkm SET evolution_code=148,evolution_condition='Level 55' WHERE pkm.pkm_code=149;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=150;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=151;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=152;
UPDATE pkm SET evolution_code=152,evolution_condition='Level 16' WHERE pkm.pkm_code=153;
UPDATE pkm SET evolution_code=153,evolution_condition='Level 32' WHERE pkm.pkm_code=154;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=155;
UPDATE pkm SET evolution_code=155,evolution_condition='Level 14' WHERE pkm.pkm_code=156;
UPDATE pkm SET evolution_code=156,evolution_condition='Level 36' WHERE pkm.pkm_code=157;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=158;
UPDATE pkm SET evolution_code=158,evolution_condition='Level 18' WHERE pkm.pkm_code=159;
UPDATE pkm SET evolution_code=159,evolution_condition='Level 30' WHERE pkm.pkm_code=160;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=161;
UPDATE pkm SET evolution_code=161,evolution_condition='Level 15' WHERE pkm.pkm_code=162;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=163;
UPDATE pkm SET evolution_code=163,evolution_condition='Level 20' WHERE pkm.pkm_code=164;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=165;
UPDATE pkm SET evolution_code=165,evolution_condition='Level 18' WHERE pkm.pkm_code=166;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=167;
UPDATE pkm SET evolution_code=167,evolution_condition='Level 22' WHERE pkm.pkm_code=168;
UPDATE pkm SET evolution_code=42,evolution_condition='Happiness' WHERE pkm.pkm_code=169;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=170;
UPDATE pkm SET evolution_code=170,evolution_condition='Level 27' WHERE pkm.pkm_code=171;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=172;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=173;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=174;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=175;
UPDATE pkm SET evolution_code=175,evolution_condition='Happiness' WHERE pkm.pkm_code=176;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=177;
UPDATE pkm SET evolution_code=177,evolution_condition='Level 25' WHERE pkm.pkm_code=178;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=179;
UPDATE pkm SET evolution_code=179,evolution_condition='Level 15' WHERE pkm.pkm_code=180;
UPDATE pkm SET evolution_code=180,evolution_condition='Level 30' WHERE pkm.pkm_code=181;
UPDATE pkm SET evolution_code=44,evolution_condition='use Sun Stone' WHERE pkm.pkm_code=182;
UPDATE pkm SET evolution_code=298,evolution_condition='Happiness' WHERE pkm.pkm_code=183;
UPDATE pkm SET evolution_code=183,evolution_condition='Level 18' WHERE pkm.pkm_code=184;
UPDATE pkm SET evolution_code=438,evolution_condition='Level up with Mimic learned' WHERE pkm.pkm_code=185;
UPDATE pkm SET evolution_code=61,evolution_condition='Trade holding King\'s Rock' WHERE pkm.pkm_code=186;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=187;
UPDATE pkm SET evolution_code=187,evolution_condition='Level 18' WHERE pkm.pkm_code=188;
UPDATE pkm SET evolution_code=188,evolution_condition='Level 27' WHERE pkm.pkm_code=189;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=190;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=191;
UPDATE pkm SET evolution_code=191,evolution_condition='use Sun Stone' WHERE pkm.pkm_code=192;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=193;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=194;
UPDATE pkm SET evolution_code=194,evolution_condition='Level 20' WHERE pkm.pkm_code=195;
UPDATE pkm SET evolution_code=133,evolution_condition='Happiness during day' WHERE pkm.pkm_code=196;
UPDATE pkm SET evolution_code=133,evolution_condition='Happiness at night' WHERE pkm.pkm_code=197;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=198;
UPDATE pkm SET evolution_code=79,evolution_condition='Trade holding King\'s Rock' WHERE pkm.pkm_code=199;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=200;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=201;
UPDATE pkm SET evolution_code=360,evolution_condition='Level 15' WHERE pkm.pkm_code=202;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=203;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=204;
UPDATE pkm SET evolution_code=204,evolution_condition='Level 31' WHERE pkm.pkm_code=205;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=206;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=207;
UPDATE pkm SET evolution_code=95,evolution_condition='Trade holding Metal Coat' WHERE pkm.pkm_code=208;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=209;
UPDATE pkm SET evolution_code=209,evolution_condition='Level 23' WHERE pkm.pkm_code=210;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=211;
UPDATE pkm SET evolution_code=123,evolution_condition='Trade holding Metal Coat' WHERE pkm.pkm_code=212;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=213;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=214;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=215;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=216;
UPDATE pkm SET evolution_code=216,evolution_condition='Level 30' WHERE pkm.pkm_code=217;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=218;
UPDATE pkm SET evolution_code=218,evolution_condition='Level 38' WHERE pkm.pkm_code=219;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=220;
UPDATE pkm SET evolution_code=220,evolution_condition='Level 33' WHERE pkm.pkm_code=221;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=222;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=223;
UPDATE pkm SET evolution_code=223,evolution_condition='Level 25' WHERE pkm.pkm_code=224;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=225;
UPDATE pkm SET evolution_code=458,evolution_condition='Level up with Remoraid in party' WHERE pkm.pkm_code=226;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=227;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=228;
UPDATE pkm SET evolution_code=228,evolution_condition='Level 24' WHERE pkm.pkm_code=229;
UPDATE pkm SET evolution_code=117,evolution_condition='Trade holding Dragon Scale' WHERE pkm.pkm_code=230;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=231;
UPDATE pkm SET evolution_code=231,evolution_condition='Level 25' WHERE pkm.pkm_code=232;
UPDATE pkm SET evolution_code=137,evolution_condition='Trade holding Up-Grade' WHERE pkm.pkm_code=233;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=234;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=235;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=236;
UPDATE pkm SET evolution_code=236,evolution_condition='Level 20 with equal Attack and Defense' WHERE pkm.pkm_code=237;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=238;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=239;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=240;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=241;
UPDATE pkm SET evolution_code=113,evolution_condition='Happiness' WHERE pkm.pkm_code=242;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=243;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=244;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=245;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=246;
UPDATE pkm SET evolution_code=246,evolution_condition='Level 30' WHERE pkm.pkm_code=247;
UPDATE pkm SET evolution_code=247,evolution_condition='Level 55' WHERE pkm.pkm_code=248;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=249;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=250;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=251;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=252;
UPDATE pkm SET evolution_code=252,evolution_condition='Level 16' WHERE pkm.pkm_code=253;
UPDATE pkm SET evolution_code=253,evolution_condition='Level 36' WHERE pkm.pkm_code=254;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=255;
UPDATE pkm SET evolution_code=255,evolution_condition='Level 16' WHERE pkm.pkm_code=256;
UPDATE pkm SET evolution_code=256,evolution_condition='Level 36' WHERE pkm.pkm_code=257;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=258;
UPDATE pkm SET evolution_code=258,evolution_condition='Level 16' WHERE pkm.pkm_code=259;
UPDATE pkm SET evolution_code=259,evolution_condition='Level 36' WHERE pkm.pkm_code=260;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=261;
UPDATE pkm SET evolution_code=261,evolution_condition='Level 18' WHERE pkm.pkm_code=262;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=263;
UPDATE pkm SET evolution_code=263,evolution_condition='Level 20' WHERE pkm.pkm_code=264;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=265;
UPDATE pkm SET evolution_code=265,evolution_condition='\'""Level 7' WHERE pkm.pkm_code=266;
UPDATE pkm SET evolution_code=266,evolution_condition='Level 10' WHERE pkm.pkm_code=267;
UPDATE pkm SET evolution_code=265,evolution_condition='\'""Level 7' WHERE pkm.pkm_code=268;
UPDATE pkm SET evolution_code=268,evolution_condition='Level 10' WHERE pkm.pkm_code=269;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=270;
UPDATE pkm SET evolution_code=270,evolution_condition='Level 14' WHERE pkm.pkm_code=271;
UPDATE pkm SET evolution_code=271,evolution_condition='use Water Stone' WHERE pkm.pkm_code=272;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=273;
UPDATE pkm SET evolution_code=273,evolution_condition='Level 14' WHERE pkm.pkm_code=274;
UPDATE pkm SET evolution_code=274,evolution_condition='use Leaf Stone' WHERE pkm.pkm_code=275;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=276;
UPDATE pkm SET evolution_code=276,evolution_condition='Level 22' WHERE pkm.pkm_code=277;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=278;
UPDATE pkm SET evolution_code=278,evolution_condition='Level 25' WHERE pkm.pkm_code=279;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=280;
UPDATE pkm SET evolution_code=280,evolution_condition='Level 20' WHERE pkm.pkm_code=281;
UPDATE pkm SET evolution_code=281,evolution_condition='Level 30' WHERE pkm.pkm_code=282;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=283;
UPDATE pkm SET evolution_code=283,evolution_condition='Level 22' WHERE pkm.pkm_code=284;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=285;
UPDATE pkm SET evolution_code=285,evolution_condition='Level 23' WHERE pkm.pkm_code=286;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=287;
UPDATE pkm SET evolution_code=287,evolution_condition='Level 18' WHERE pkm.pkm_code=288;
UPDATE pkm SET evolution_code=288,evolution_condition='Level 36' WHERE pkm.pkm_code=289;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=290;
UPDATE pkm SET evolution_code=290,evolution_condition='Level 20' WHERE pkm.pkm_code=291;
UPDATE pkm SET evolution_code=290,evolution_condition='Level 20 with an empty spot in party and a Pokeball in bag ' WHERE pkm.pkm_code=292;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=293;
UPDATE pkm SET evolution_code=293,evolution_condition='Level 20' WHERE pkm.pkm_code=294;
UPDATE pkm SET evolution_code=294,evolution_condition='Level 40' WHERE pkm.pkm_code=295;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=296;
UPDATE pkm SET evolution_code=296,evolution_condition='Level 24' WHERE pkm.pkm_code=297;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=298;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=299;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=300;
UPDATE pkm SET evolution_code=300,evolution_condition='use Moon Stone' WHERE pkm.pkm_code=301;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=302;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=303;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=304;
UPDATE pkm SET evolution_code=304,evolution_condition='Level 32' WHERE pkm.pkm_code=305;
UPDATE pkm SET evolution_code=305,evolution_condition='Level 42' WHERE pkm.pkm_code=306;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=307;
UPDATE pkm SET evolution_code=307,evolution_condition='Level 37' WHERE pkm.pkm_code=308;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=309;
UPDATE pkm SET evolution_code=309,evolution_condition='Level 26' WHERE pkm.pkm_code=310;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=311;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=312;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=313;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=314;
UPDATE pkm SET evolution_code=406,evolution_condition='Happiness during day' WHERE pkm.pkm_code=315;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=316;
UPDATE pkm SET evolution_code=316,evolution_condition='Level 26' WHERE pkm.pkm_code=317;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=318;
UPDATE pkm SET evolution_code=318,evolution_condition='Level 30' WHERE pkm.pkm_code=319;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=320;
UPDATE pkm SET evolution_code=320,evolution_condition='Level 40' WHERE pkm.pkm_code=321;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=322;
UPDATE pkm SET evolution_code=322,evolution_condition='Level 33' WHERE pkm.pkm_code=323;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=324;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=325;
UPDATE pkm SET evolution_code=325,evolution_condition='Level 32' WHERE pkm.pkm_code=326;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=327;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=328;
UPDATE pkm SET evolution_code=328,evolution_condition='Level 35' WHERE pkm.pkm_code=329;
UPDATE pkm SET evolution_code=329,evolution_condition='Level 45' WHERE pkm.pkm_code=330;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=331;
UPDATE pkm SET evolution_code=331,evolution_condition='Level 32' WHERE pkm.pkm_code=332;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=333;
UPDATE pkm SET evolution_code=333,evolution_condition='Level 35' WHERE pkm.pkm_code=334;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=335;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=336;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=337;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=338;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=339;
UPDATE pkm SET evolution_code=339,evolution_condition='Level 30' WHERE pkm.pkm_code=340;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=341;
UPDATE pkm SET evolution_code=341,evolution_condition='Level 30' WHERE pkm.pkm_code=342;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=343;
UPDATE pkm SET evolution_code=343,evolution_condition='Level 36' WHERE pkm.pkm_code=344;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=345;
UPDATE pkm SET evolution_code=345,evolution_condition='Level 40' WHERE pkm.pkm_code=346;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=347;
UPDATE pkm SET evolution_code=347,evolution_condition='Level 40' WHERE pkm.pkm_code=348;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=349;
UPDATE pkm SET evolution_code=349,evolution_condition='Level up with max Beauty or Trade holding Prism Scale' WHERE pkm.pkm_code=350;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=351;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=352;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=353;
UPDATE pkm SET evolution_code=353,evolution_condition='Level 37' WHERE pkm.pkm_code=354;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=355;
UPDATE pkm SET evolution_code=355,evolution_condition='Level 37' WHERE pkm.pkm_code=356;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=357;
UPDATE pkm SET evolution_code=433,evolution_condition='Happiness at night' WHERE pkm.pkm_code=358;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=359;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=360;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=361;
UPDATE pkm SET evolution_code=361,evolution_condition='Level 42' WHERE pkm.pkm_code=362;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=363;
UPDATE pkm SET evolution_code=363,evolution_condition='Level 32' WHERE pkm.pkm_code=364;
UPDATE pkm SET evolution_code=364,evolution_condition='Level 44' WHERE pkm.pkm_code=365;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=366;
UPDATE pkm SET evolution_code=366,evolution_condition='Trade holding Deepseatooth' WHERE pkm.pkm_code=367;
UPDATE pkm SET evolution_code=366,evolution_condition='Trade holding Deepseascale' WHERE pkm.pkm_code=368;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=369;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=370;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=371;
UPDATE pkm SET evolution_code=371,evolution_condition='Level 30' WHERE pkm.pkm_code=372;
UPDATE pkm SET evolution_code=372,evolution_condition='Level 50' WHERE pkm.pkm_code=373;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=374;
UPDATE pkm SET evolution_code=374,evolution_condition='Level 20' WHERE pkm.pkm_code=375;
UPDATE pkm SET evolution_code=375,evolution_condition='Level 45' WHERE pkm.pkm_code=376;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=377;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=378;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=379;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=380;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=381;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=382;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=383;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=384;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=385;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=386;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=387;
UPDATE pkm SET evolution_code=387,evolution_condition='Level 18' WHERE pkm.pkm_code=388;
UPDATE pkm SET evolution_code=388,evolution_condition='Level 32' WHERE pkm.pkm_code=389;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=390;
UPDATE pkm SET evolution_code=390,evolution_condition='Level 14' WHERE pkm.pkm_code=391;
UPDATE pkm SET evolution_code=391,evolution_condition='Level 36' WHERE pkm.pkm_code=392;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=393;
UPDATE pkm SET evolution_code=393,evolution_condition='Level 16' WHERE pkm.pkm_code=394;
UPDATE pkm SET evolution_code=394,evolution_condition='Level 36' WHERE pkm.pkm_code=395;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=396;
UPDATE pkm SET evolution_code=396,evolution_condition='Level 14' WHERE pkm.pkm_code=397;
UPDATE pkm SET evolution_code=397,evolution_condition='Level 34' WHERE pkm.pkm_code=398;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=399;
UPDATE pkm SET evolution_code=399,evolution_condition='Level 15' WHERE pkm.pkm_code=400;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=401;
UPDATE pkm SET evolution_code=401,evolution_condition='Level 10' WHERE pkm.pkm_code=402;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=403;
UPDATE pkm SET evolution_code=403,evolution_condition='Level 15' WHERE pkm.pkm_code=404;
UPDATE pkm SET evolution_code=404,evolution_condition='Level 30' WHERE pkm.pkm_code=405;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=406;
UPDATE pkm SET evolution_code=315,evolution_condition='use Shiny Stone' WHERE pkm.pkm_code=407;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=408;
UPDATE pkm SET evolution_code=408,evolution_condition='Level 30' WHERE pkm.pkm_code=409;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=410;
UPDATE pkm SET evolution_code=410,evolution_condition='Level 30' WHERE pkm.pkm_code=411;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=412;
UPDATE pkm SET evolution_code=412,evolution_condition='Level 20 and Female' WHERE pkm.pkm_code=413;
UPDATE pkm SET evolution_code=413,evolution_condition='Level 20 and Male' WHERE pkm.pkm_code=414;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=415;
UPDATE pkm SET evolution_code=415,evolution_condition='Level 21 and Female' WHERE pkm.pkm_code=416;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=417;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=418;
UPDATE pkm SET evolution_code=418,evolution_condition='Level 26' WHERE pkm.pkm_code=419;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=420;
UPDATE pkm SET evolution_code=420,evolution_condition='Level 25' WHERE pkm.pkm_code=421;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=422;
UPDATE pkm SET evolution_code=422,evolution_condition='Level 30' WHERE pkm.pkm_code=423;
UPDATE pkm SET evolution_code=190,evolution_condition='Level up with Double Hit learned' WHERE pkm.pkm_code=424;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=425;
UPDATE pkm SET evolution_code=425,evolution_condition='Level 28' WHERE pkm.pkm_code=426;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=427;
UPDATE pkm SET evolution_code=427,evolution_condition='Happiness' WHERE pkm.pkm_code=428;
UPDATE pkm SET evolution_code=200,evolution_condition='use Dusk Stone' WHERE pkm.pkm_code=429;
UPDATE pkm SET evolution_code=198,evolution_condition='use Dusk Stone' WHERE pkm.pkm_code=430;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=431;
UPDATE pkm SET evolution_code=431,evolution_condition='Level 38' WHERE pkm.pkm_code=432;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=433;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=434;
UPDATE pkm SET evolution_code=434,evolution_condition='Level 34' WHERE pkm.pkm_code=435;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=436;
UPDATE pkm SET evolution_code=436,evolution_condition='Level 33' WHERE pkm.pkm_code=437;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=438;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=439;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=440;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=441;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=442;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=443;
UPDATE pkm SET evolution_code=443,evolution_condition='Level 24' WHERE pkm.pkm_code=444;
UPDATE pkm SET evolution_code=444,evolution_condition='Level 48' WHERE pkm.pkm_code=445;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=446;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=447;
UPDATE pkm SET evolution_code=447,evolution_condition='Happiness during day' WHERE pkm.pkm_code=448;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=449;
UPDATE pkm SET evolution_code=449,evolution_condition='Level 34' WHERE pkm.pkm_code=450;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=451;
UPDATE pkm SET evolution_code=451,evolution_condition='Level 40' WHERE pkm.pkm_code=452;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=453;
UPDATE pkm SET evolution_code=453,evolution_condition='Level 37' WHERE pkm.pkm_code=454;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=455;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=456;
UPDATE pkm SET evolution_code=456,evolution_condition='Level 31' WHERE pkm.pkm_code=457;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=458;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=459;
UPDATE pkm SET evolution_code=459,evolution_condition='Level 40' WHERE pkm.pkm_code=460;
UPDATE pkm SET evolution_code=215,evolution_condition='Level up holding Razor Claw at night' WHERE pkm.pkm_code=461;
UPDATE pkm SET evolution_code=82,evolution_condition='Level up in a Magnetic field area' WHERE pkm.pkm_code=462;
UPDATE pkm SET evolution_code=108,evolution_condition='Level up with Rollout learned' WHERE pkm.pkm_code=463;
UPDATE pkm SET evolution_code=112,evolution_condition='Trade holding Protector' WHERE pkm.pkm_code=464;
UPDATE pkm SET evolution_code=114,evolution_condition='Level up with Ancient Power learned' WHERE pkm.pkm_code=465;
UPDATE pkm SET evolution_code=125,evolution_condition='Trade holding Electrizer' WHERE pkm.pkm_code=466;
UPDATE pkm SET evolution_code=126,evolution_condition='Trade holding Magmarizer' WHERE pkm.pkm_code=467;
UPDATE pkm SET evolution_code=176,evolution_condition='use Shiny Stone' WHERE pkm.pkm_code=468;
UPDATE pkm SET evolution_code=193,evolution_condition='Level up with Ancient Power learned' WHERE pkm.pkm_code=469;
UPDATE pkm SET evolution_code=133,evolution_condition='Level up near Moss Rock' WHERE pkm.pkm_code=470;
UPDATE pkm SET evolution_code=133,evolution_condition='Level up near Ice Rock' WHERE pkm.pkm_code=471;
UPDATE pkm SET evolution_code=207,evolution_condition='Level up holding Razor Fang at night' WHERE pkm.pkm_code=472;
UPDATE pkm SET evolution_code=221,evolution_condition='Level up with Ancient Power learned' WHERE pkm.pkm_code=473;
UPDATE pkm SET evolution_code=233,evolution_condition='Trade holding Dubious Disk' WHERE pkm.pkm_code=474;
UPDATE pkm SET evolution_code=281,evolution_condition='use Dawn Stone and Male' WHERE pkm.pkm_code=475;
UPDATE pkm SET evolution_code=299,evolution_condition='Level up in a Magnetic Field area' WHERE pkm.pkm_code=476;
UPDATE pkm SET evolution_code=356,evolution_condition='Trade holding Reaper Cloth' WHERE pkm.pkm_code=477;
UPDATE pkm SET evolution_code=361,evolution_condition='use Dawn Stone and Female' WHERE pkm.pkm_code=478;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=479;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=480;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=481;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=482;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=483;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=484;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=485;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=486;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=487;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=488;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=489;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=490;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=491;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=492;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=493;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=494;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=495;
UPDATE pkm SET evolution_code=495,evolution_condition='Level 17' WHERE pkm.pkm_code=496;
UPDATE pkm SET evolution_code=496,evolution_condition='Level 36' WHERE pkm.pkm_code=497;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=498;
UPDATE pkm SET evolution_code=498,evolution_condition='Level 17' WHERE pkm.pkm_code=499;
UPDATE pkm SET evolution_code=499,evolution_condition='Level 36' WHERE pkm.pkm_code=500;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=501;
UPDATE pkm SET evolution_code=501,evolution_condition='Level 17' WHERE pkm.pkm_code=502;
UPDATE pkm SET evolution_code=502,evolution_condition='Level 36' WHERE pkm.pkm_code=503;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=504;
UPDATE pkm SET evolution_code=504,evolution_condition='Level 20' WHERE pkm.pkm_code=505;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=506;
UPDATE pkm SET evolution_code=506,evolution_condition='Level 16' WHERE pkm.pkm_code=507;
UPDATE pkm SET evolution_code=507,evolution_condition='Level 32' WHERE pkm.pkm_code=508;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=509;
UPDATE pkm SET evolution_code=509,evolution_condition='Level 20' WHERE pkm.pkm_code=510;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=511;
UPDATE pkm SET evolution_code=511,evolution_condition='use Leaf Stone' WHERE pkm.pkm_code=512;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=513;
UPDATE pkm SET evolution_code=513,evolution_condition='use Fire Stone' WHERE pkm.pkm_code=514;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=515;
UPDATE pkm SET evolution_code=515,evolution_condition='use Water Stone' WHERE pkm.pkm_code=516;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=517;
UPDATE pkm SET evolution_code=517,evolution_condition='use Moon Stone' WHERE pkm.pkm_code=518;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=519;
UPDATE pkm SET evolution_code=519,evolution_condition='Level 21' WHERE pkm.pkm_code=520;
UPDATE pkm SET evolution_code=520,evolution_condition='Level 32' WHERE pkm.pkm_code=521;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=522;
UPDATE pkm SET evolution_code=522,evolution_condition='Level 27' WHERE pkm.pkm_code=523;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=524;
UPDATE pkm SET evolution_code=524,evolution_condition='Level 25' WHERE pkm.pkm_code=525;
UPDATE pkm SET evolution_code=525,evolution_condition='Trade' WHERE pkm.pkm_code=526;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=527;
UPDATE pkm SET evolution_code=527,evolution_condition='Happiness' WHERE pkm.pkm_code=528;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=529;
UPDATE pkm SET evolution_code=529,evolution_condition='Level 31' WHERE pkm.pkm_code=530;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=531;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=532;
UPDATE pkm SET evolution_code=532,evolution_condition='Level 25' WHERE pkm.pkm_code=533;
UPDATE pkm SET evolution_code=533,evolution_condition='Trade' WHERE pkm.pkm_code=534;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=535;
UPDATE pkm SET evolution_code=535,evolution_condition='Level 25' WHERE pkm.pkm_code=536;
UPDATE pkm SET evolution_code=536,evolution_condition='Level 36' WHERE pkm.pkm_code=537;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=538;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=539;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=540;
UPDATE pkm SET evolution_code=540,evolution_condition='Level 20' WHERE pkm.pkm_code=541;
UPDATE pkm SET evolution_code=541,evolution_condition='Happiness' WHERE pkm.pkm_code=542;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=543;
UPDATE pkm SET evolution_code=543,evolution_condition='Level 22' WHERE pkm.pkm_code=544;
UPDATE pkm SET evolution_code=544,evolution_condition='Level 30' WHERE pkm.pkm_code=545;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=546;
UPDATE pkm SET evolution_code=546,evolution_condition='use Sun Stone' WHERE pkm.pkm_code=547;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=548;
UPDATE pkm SET evolution_code=548,evolution_condition='use Sun Stone' WHERE pkm.pkm_code=549;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=550;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=551;
UPDATE pkm SET evolution_code=551,evolution_condition='Level 29' WHERE pkm.pkm_code=552;
UPDATE pkm SET evolution_code=552,evolution_condition='Level 40' WHERE pkm.pkm_code=553;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=554;
UPDATE pkm SET evolution_code=554,evolution_condition='Level 35' WHERE pkm.pkm_code=555;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=556;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=557;
UPDATE pkm SET evolution_code=557,evolution_condition='Level 34' WHERE pkm.pkm_code=558;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=559;
UPDATE pkm SET evolution_code=559,evolution_condition='Level 39' WHERE pkm.pkm_code=560;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=561;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=562;
UPDATE pkm SET evolution_code=562,evolution_condition='Level 34' WHERE pkm.pkm_code=563;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=564;
UPDATE pkm SET evolution_code=564,evolution_condition='Level 37' WHERE pkm.pkm_code=565;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=566;
UPDATE pkm SET evolution_code=566,evolution_condition='Level 37' WHERE pkm.pkm_code=567;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=568;
UPDATE pkm SET evolution_code=568,evolution_condition='Level 36' WHERE pkm.pkm_code=569;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=570;
UPDATE pkm SET evolution_code=570,evolution_condition='Level 30' WHERE pkm.pkm_code=571;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=572;
UPDATE pkm SET evolution_code=572,evolution_condition='use Shiny Stone' WHERE pkm.pkm_code=573;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=574;
UPDATE pkm SET evolution_code=574,evolution_condition='Level 32' WHERE pkm.pkm_code=575;
UPDATE pkm SET evolution_code=575,evolution_condition='Level 41' WHERE pkm.pkm_code=576;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=577;
UPDATE pkm SET evolution_code=577,evolution_condition='Level 32' WHERE pkm.pkm_code=578;
UPDATE pkm SET evolution_code=578,evolution_condition='Level 41' WHERE pkm.pkm_code=579;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=580;
UPDATE pkm SET evolution_code=580,evolution_condition='Level 35' WHERE pkm.pkm_code=581;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=582;
UPDATE pkm SET evolution_code=582,evolution_condition='Level 35' WHERE pkm.pkm_code=583;
UPDATE pkm SET evolution_code=583,evolution_condition='Level 47' WHERE pkm.pkm_code=584;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=585;
UPDATE pkm SET evolution_code=585,evolution_condition='Level 34' WHERE pkm.pkm_code=586;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=587;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=588;
UPDATE pkm SET evolution_code=588,evolution_condition='Trade with Shelmet' WHERE pkm.pkm_code=589;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=590;
UPDATE pkm SET evolution_code=590,evolution_condition='Level 39' WHERE pkm.pkm_code=591;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=592;
UPDATE pkm SET evolution_code=592,evolution_condition='Level 40' WHERE pkm.pkm_code=593;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=594;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=595;
UPDATE pkm SET evolution_code=595,evolution_condition='Level 36' WHERE pkm.pkm_code=596;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=597;
UPDATE pkm SET evolution_code=597,evolution_condition='Level 40' WHERE pkm.pkm_code=598;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=599;
UPDATE pkm SET evolution_code=599,evolution_condition='Level 38' WHERE pkm.pkm_code=600;
UPDATE pkm SET evolution_code=600,evolution_condition='Level 49' WHERE pkm.pkm_code=601;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=602;
UPDATE pkm SET evolution_code=602,evolution_condition='Level 39' WHERE pkm.pkm_code=603;
UPDATE pkm SET evolution_code=603,evolution_condition='use Thunder Stone' WHERE pkm.pkm_code=604;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=605;
UPDATE pkm SET evolution_code=605,evolution_condition='Level 42' WHERE pkm.pkm_code=606;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=607;
UPDATE pkm SET evolution_code=607,evolution_condition='Level 41' WHERE pkm.pkm_code=608;
UPDATE pkm SET evolution_code=608,evolution_condition='use Dusk Stone' WHERE pkm.pkm_code=609;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=610;
UPDATE pkm SET evolution_code=610,evolution_condition='Level 38' WHERE pkm.pkm_code=611;
UPDATE pkm SET evolution_code=611,evolution_condition='Level 48' WHERE pkm.pkm_code=612;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=613;
UPDATE pkm SET evolution_code=613,evolution_condition='Level 37' WHERE pkm.pkm_code=614;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=615;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=616;
UPDATE pkm SET evolution_code=616,evolution_condition='Trade with Karrablast' WHERE pkm.pkm_code=617;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=618;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=619;
UPDATE pkm SET evolution_code=619,evolution_condition='Level 50' WHERE pkm.pkm_code=620;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=621;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=622;
UPDATE pkm SET evolution_code=622,evolution_condition='Level 43' WHERE pkm.pkm_code=623;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=624;
UPDATE pkm SET evolution_code=624,evolution_condition='Level 52' WHERE pkm.pkm_code=625;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=626;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=627;
UPDATE pkm SET evolution_code=627,evolution_condition='Level 54' WHERE pkm.pkm_code=628;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=629;
UPDATE pkm SET evolution_code=629,evolution_condition='Level 54' WHERE pkm.pkm_code=630;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=631;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=632;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=633;
UPDATE pkm SET evolution_code=633,evolution_condition='Level 50' WHERE pkm.pkm_code=634;
UPDATE pkm SET evolution_code=634,evolution_condition='Level 64' WHERE pkm.pkm_code=635;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=636;
UPDATE pkm SET evolution_code=636,evolution_condition='Level 59' WHERE pkm.pkm_code=637;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=638;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=639;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=640;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=641;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=642;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=643;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=644;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=645;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=646;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=647;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=648;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=649;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=650;
UPDATE pkm SET evolution_code=650,evolution_condition='Level 16' WHERE pkm.pkm_code=651;
UPDATE pkm SET evolution_code=651,evolution_condition='Level 36' WHERE pkm.pkm_code=652;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=653;
UPDATE pkm SET evolution_code=653,evolution_condition='Level 16' WHERE pkm.pkm_code=654;
UPDATE pkm SET evolution_code=654,evolution_condition='Level 36' WHERE pkm.pkm_code=655;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=656;
UPDATE pkm SET evolution_code=656,evolution_condition='Level 16' WHERE pkm.pkm_code=657;
UPDATE pkm SET evolution_code=657,evolution_condition='Level 36' WHERE pkm.pkm_code=658;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=659;
UPDATE pkm SET evolution_code=659,evolution_condition='Level 20' WHERE pkm.pkm_code=660;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=661;
UPDATE pkm SET evolution_code=661,evolution_condition='Level 17' WHERE pkm.pkm_code=662;
UPDATE pkm SET evolution_code=662,evolution_condition='Level 35' WHERE pkm.pkm_code=663;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=664;
UPDATE pkm SET evolution_code=664,evolution_condition='Level 9' WHERE pkm.pkm_code=665;
UPDATE pkm SET evolution_code=665,evolution_condition='Level 12' WHERE pkm.pkm_code=666;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=667;
UPDATE pkm SET evolution_code=667,evolution_condition='Level 35' WHERE pkm.pkm_code=668;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=669;
UPDATE pkm SET evolution_code=669,evolution_condition='Level 19' WHERE pkm.pkm_code=670;
UPDATE pkm SET evolution_code=670,evolution_condition='use Shiny Stone' WHERE pkm.pkm_code=671;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=672;
UPDATE pkm SET evolution_code=672,evolution_condition='Level 32' WHERE pkm.pkm_code=673;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=674;
UPDATE pkm SET evolution_code=674,evolution_condition='Level 32 with a Dark type Pokemon in party' WHERE pkm.pkm_code=675;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=676;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=677;
UPDATE pkm SET evolution_code=677,evolution_condition='Level 25' WHERE pkm.pkm_code=678;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=679;
UPDATE pkm SET evolution_code=679,evolution_condition='Level 35' WHERE pkm.pkm_code=680;
UPDATE pkm SET evolution_code=680,evolution_condition='use Dusk Stone' WHERE pkm.pkm_code=681;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=682;
UPDATE pkm SET evolution_code=682,evolution_condition='Trade holding Sachet' WHERE pkm.pkm_code=683;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=684;
UPDATE pkm SET evolution_code=684,evolution_condition='Trade holding Whipped Dream' WHERE pkm.pkm_code=685;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=686;
UPDATE pkm SET evolution_code=686,evolution_condition='Level 30 holding 3DS upside down' WHERE pkm.pkm_code=687;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=688;
UPDATE pkm SET evolution_code=688,evolution_condition='Level 39' WHERE pkm.pkm_code=689;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=690;
UPDATE pkm SET evolution_code=690,evolution_condition='Level 48' WHERE pkm.pkm_code=691;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=692;
UPDATE pkm SET evolution_code=692,evolution_condition='Level 37' WHERE pkm.pkm_code=693;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=694;
UPDATE pkm SET evolution_code=694,evolution_condition='use Sun Stone' WHERE pkm.pkm_code=695;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=696;
UPDATE pkm SET evolution_code=696,evolution_condition='Level 39 during day' WHERE pkm.pkm_code=697;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=698;
UPDATE pkm SET evolution_code=698,evolution_condition='Level 39 at night' WHERE pkm.pkm_code=699;
UPDATE pkm SET evolution_code=133,evolution_condition='Level up with 2 Affection hearts in Pokemon-Amie and know a Fairy-type move' WHERE pkm.pkm_code=700;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=701;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=702;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=703;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=704;
UPDATE pkm SET evolution_code=704,evolution_condition='Level 40' WHERE pkm.pkm_code=705;
UPDATE pkm SET evolution_code=705,evolution_condition='Level 50 during rain' WHERE pkm.pkm_code=706;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=707;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=708;
UPDATE pkm SET evolution_code=708,evolution_condition='Trade' WHERE pkm.pkm_code=709;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=710;
UPDATE pkm SET evolution_code=710,evolution_condition='Trade' WHERE pkm.pkm_code=711;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=712;
UPDATE pkm SET evolution_code=712,evolution_condition='Level 37' WHERE pkm.pkm_code=713;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=714;
UPDATE pkm SET evolution_code=714,evolution_condition='Level 48' WHERE pkm.pkm_code=715;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=716;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=717;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=718;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=719;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=720;
UPDATE pkm SET evolution_code=NULL,evolution_condition=NULL WHERE pkm.pkm_code=721;
